// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

import openAPISideBar from "./docs/openapi-doc/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.



 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "مستندات API",
      link: {
        type: "generated-index",
        title: "مستندات API(Swgger)",
        slug: "/kenar-docs/openapi-doc",
        keywords: ["api", "api doc", "openapi"]
      },
      items: openAPISideBar,
    },
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'پنل کنار',
      href: 'https://divar.ir/kenar',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
