import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "openapi-doc/kenar-api",
    },
    {
      type: "category",
      label: "Addons",
      link: {
        type: "doc",
        id: "openapi-doc/addons",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/addons-delete-post-addon",
          label: "حذف افزونه از آگهی",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-create-business-addon",
          label: "افزودن افزونه جدید به آگهی‌های کسب‌و‌کار",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-delete-post-addon-2",
          label: "حذف افزونه از آگهی",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-delete-user-addon",
          label: "حذف افزونه کاربر",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-get-user-addons",
          label: "دریافت تمام افزونه‌های کاربر",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-create-post-addon-v-2",
          label: "افزودن افزونه جدید به آگهی",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-create-user-addon-v-2",
          label: "افزودن افزونه جدید به کاربر",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-get-user-addons-2",
          label: "دریافت تمام افزونه‌های کاربر",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/addons-create-user-addon-v-22",
          label: "افزودن افزونه جدید به کاربر",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Assets",
      link: {
        type: "doc",
        id: "openapi-doc/assets",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/assets-get-body-statuses",
          label: "دریافت گزینه‌های وضعیت بدنه موجود در دسته‌بندی‌های خودرو دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-brand-models",
          label: "دریافت مدل‌های برند در دسته‌بندی دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-categories",
          label: "دریافت دسته‌بندی‌های دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-cities",
          label: "دریافت شهرهای دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-colors",
          label: "دریافت رنگ‌ها در دسته‌بندی دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-districts",
          label: "دریافت مناطق دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-districts-2",
          label: "دریافت مناطق دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-internal-storages",
          label: "دریافت گزینه‌های حافظه داخلی موجود در دسته‌بندی‌های موبایل/تبلت/لپ‌تاپ دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-o-auth-scopes",
          label: "دریافت دامنه‌های OAuth کنار دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-permissions",
          label: "دریافت مجوزهای کنار دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-ram-memories",
          label: "دریافت گزینه‌های حافظه رم موجود در دسته‌بندی‌های موبایل/تبلت/لپ‌تاپ دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/assets-get-service-types",
          label: "دریافت انواع سرویس موجود در کنار دیوار",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ChatAPI",
      link: {
        type: "doc",
        id: "openapi-doc/chat-api",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/chat-api-chat-bot-send-message-5",
          label: "ارسال پیام به مکالمه ChatBot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-chat-bot-send-message-4",
          label: "ارسال پیام به مکالمه ChatBot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-generate-upload-token",
          label: "تولید توکن آپلود",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-chat-bot-send-message-3",
          label: "ارسال پیام به مکالمه ChatBot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-chat-bot-send-message",
          label: "ارسال پیام به مکالمه ChatBot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-chat-bot-send-message-2",
          label: "ارسال پیام به مکالمه ChatBot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-get-conversation",
          label: "دریافت مکالمه با شناسه آن",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/chat-api-conversation-send-message",
          label: "ارسال پیام به مکالمه",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      link: {
        type: "doc",
        id: "openapi-doc/events",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/events-send-event",
          label: "Send an event to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/events-register-event-subscription",
          label: "اشتراک در رویداد",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Finder",
      link: {
        type: "doc",
        id: "openapi-doc/finder",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/finder-get-post",
          label: "دریافت آگهی دیوار",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/finder-get-user-posts",
          label: "دریافت آگهی‌های کاربر",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/finder-get-user-2",
          label: "دریافت اطلاعات کاربر",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/finder-get-user",
          label: "دریافت اطلاعات کاربر",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/finder-search-post-v-2",
          label: "جستجو آگهی‌های دیوار با فیلترهایی",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Post",
      link: {
        type: "doc",
        id: "openapi-doc/post",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/post-submit-emergency-residence-post",
          label: "Submit an emergency residence post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/post-submit-post",
          label: "Submit a post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/post-get-post-stats",
          label: "دریافت آمارهای آگهی",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/post-get-image-upload-url",
          label: "دریافت URL آپلود تصویر",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/post-edit-post",
          label: "ویرایش آگهی",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "limited",
      link: {
        type: "doc",
        id: "openapi-doc/limited",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/payment-get-balance",
          label: "Payment_GetBalance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/payment-reorder-post",
          label: "Payment_ReorderPost",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/payment-list-transactions",
          label: "Payment_ListTransactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/payment-get-transaction",
          label: "Payment_GetTransaction",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi-doc/payment-get-post-pricing",
          label: "دریافت هزینه سرویس",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "PaymentTicket",
      link: {
        type: "doc",
        id: "openapi-doc/payment-ticket",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/payment-ticket-validate",
          label: "اعتبارسنجی بلیط پرداخت",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Semantic",
      link: {
        type: "doc",
        id: "openapi-doc/semantic",
      },
      items: [
        {
          type: "doc",
          id: "openapi-doc/semantic-create-post-semantic",
          label: "ایجاد اطلاعات معنایی آگهی",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/semantic-delete-user-semantic",
          label: "حذف اطلاعات معنایی کاربر",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi-doc/semantic-create-user-semantic",
          label: "ایجاد اطلاعات معنایی کاربر",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi-doc/semantic-delete-user-semantic-2",
          label: "حذف اطلاعات معنایی کاربر",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi-doc/semantic-create-user-semantic-2",
          label: "ایجاد اطلاعات معنایی کاربر",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsecondarylinkageposition",
          label: "AddonSecondaryLinkagePosition",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticcarverificationstage",
          label: "AddonSemanticCarVerificationStage",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/face-and-id-matched-id-به-معنای-کارت-ملی-است،-این-مقدار-منجر-به-نشان-در-تطبیق-می-شود",
          label: "- FACE_AND_ID_MATCHED: ID به معنای کارت ملی است، این مقدار منجر به نشان در تطبیق می‌شود",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticidentityverificationstage",
          label: "AddonSemanticIdentityVerificationStage",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticinspectionresult",
          label: "AddonSemanticInspectionResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticnewfaceverificationresult",
          label: "AddonSemanticNewFaceVerificationResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticownershipresult",
          label: "AddonSemanticOwnershipResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsemanticpostverificationresult",
          label: "AddonSemanticPostVerificationResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreatebusinessaddonbody",
          label: "AddonsCreateBusinessAddonBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreatepostaddonv-2-body",
          label: "AddonsCreatePostAddonV2Body",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreateuseraddonv-2-body",
          label: "AddonsCreateUserAddonV2Body",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapichatbotsendmessagebody",
          label: "ChatAPIChatBotSendMessageBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapiconversationsendmessagebody",
          label: "ChatAPIConversationSendMessageBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/divariconsiconname",
          label: "DivarIconsIconName",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/getpostpricingresponsereorder",
          label: "GetPostPricingResponseReorder",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/getpostresponsebusinessdata",
          label: "GetPostResponseBusinessData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/getpoststatsresponsedailystats",
          label: "GetPostStatsResponseDailyStats",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/getpoststatsresponsepoststats",
          label: "GetPostStatsResponsePostStats",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/getservicetypesresponseservicetypedata",
          label: "GetServiceTypesResponseServiceTypeData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/imagecarouselrowimageitem",
          label: "ImageCarouselRowImageItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messagefiledata",
          label: "MessageFileData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messageimagedata",
          label: "MessageImageData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messagelocationdata",
          label: "MessageLocationData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messagesender",
          label: "MessageSender",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messagevideodata",
          label: "MessageVideoData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/messagevoicedata",
          label: "MessageVoiceData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/oauthscopescope",
          label: "OAuthScopeScope",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentreorderpostbody",
          label: "PaymentReorderPostBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/posteditpostbody",
          label: "PostEditPostBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/premiumpanelbusinessdatasubbusinesstype",
          label: "PremiumPanelBusinessDataSubBusinessType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemcommunityfields",
          label: "SearchPostItemCommunityFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemelectronicdevicesfields",
          label: "SearchPostItemElectronicDevicesFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemhomekitchenfields",
          label: "SearchPostItemHomeKitchenFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemjobsfields",
          label: "SearchPostItemJobsFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemleisurehobbiesfields",
          label: "SearchPostItemLeisureHobbiesFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitempersonalgoodsfields",
          label: "SearchPostItemPersonalGoodsFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemprice",
          label: "SearchPostItemPrice",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemrealestatefields",
          label: "SearchPostItemRealEstateFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemservicesfields",
          label: "SearchPostItemServicesFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemtoolsmaterialsequipmentfields",
          label: "SearchPostItemToolsMaterialsEquipmentFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/searchpostitemvehiclesfields",
          label: "SearchPostItemVehiclesFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticcreatepostsemanticbody",
          label: "SemanticCreatePostSemanticBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticcreateusersemanticbody",
          label: "SemanticCreateUserSemanticBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/sendeventrequesttargettype",
          label: "SendEventRequestTargetType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/temporaryresidencefieldsroomscount",
          label: "TemporaryResidenceFieldsRoomsCount",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/action",
          label: "Action",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonlinkage",
          label: "addonsAddonLinkage",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonmetadata",
          label: "addonsAddonMetaData",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonsecondarylinkage",
          label: "addonsAddonSecondaryLinkage",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonsecondarylinks",
          label: "addonsAddonSecondaryLinks",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/and-post-is-selected-by-this-selector-if-all-of-the-following-conditions-matches",
          label: "(AND) post is selected by this selector if all of the following conditions\nmatches",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonsemantic",
          label: "addonsAddonSemantic",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/secure-این-مقدار-منجر-به-نشان-در-تطبیق-می-شود",
          label: "- SECURE: این مقدار منجر به نشان در تطبیق می‌شود",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsaddonsemanticstatus",
          label: "addonsAddonSemanticStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsbackfillbusinessaddonresponse",
          label: "addonsBackFillBusinessAddonResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsbusinessaddon",
          label: "addonsBusinessAddon",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsbuttonbar",
          label: "addonsButtonBar",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreatebusinessaddonresponse",
          label: "addonsCreateBusinessAddonResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreatepostaddonrequest",
          label: "addonsCreatePostAddonRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreatepostaddonresponsev-2",
          label: "addonsCreatePostAddonResponseV2",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonscreateuseraddonresponsev-2",
          label: "addonsCreateUserAddonResponseV2",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsdescriptionrow",
          label: "addonsDescriptionRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsevaluationrow",
          label: "addonsEvaluationRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsevaluationrowsection",
          label: "addonsEvaluationRowSection",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonseventrow",
          label: "addonsEventRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgetbusinessaddonsresponse",
          label: "addonsGetBusinessAddonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/get-dynamic-action",
          label: "Get Dynamic Action",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgetpostaddonsresponse",
          label: "addonsGetPostAddonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgetuseraddonsresponse",
          label: "addonsGetUserAddonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgetuserpostaddonsresponse",
          label: "addonsGetUserPostAddonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgroupinforow",
          label: "addonsGroupInfoRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsgroupinforowgroupinfoitem",
          label: "addonsGroupInfoRowGroupInfoItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsimagecarouselrow",
          label: "addonsImageCarouselRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/open-post-manage-page",
          label: "Open Post Manage Page",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/open-post-page",
          label: "Open Post Page",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/open-server-link",
          label: "Open Server Link",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonspostaddon",
          label: "addonsPostAddon",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsscorerow",
          label: "addonsScoreRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsselectorrow",
          label: "addonsSelectorRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonssendaddondeletioneventsresponse",
          label: "addonsSendAddonDeletionEventsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsstatus",
          label: "addonsStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonssubtitlerow",
          label: "addonsSubtitleRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonstitlerow",
          label: "addonsTitleRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsuseraddon",
          label: "addonsUserAddon",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonsuseraddonfilters",
          label: "addonsUserAddonFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonswidget",
          label: "addonsWidget",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonswidgetcolor",
          label: "addonsWidgetColor",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/addonswidgets",
          label: "addonsWidgets",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/appsapp",
          label: "appsApp",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/appsappstatus",
          label: "appsAppStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/appsappstatusstatus",
          label: "appsAppStatusStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/appsservicetag",
          label: "appsServiceTag",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/appsservicetype",
          label: "appsServiceType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsenumoption",
          label: "assetsEnumOption",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetbodystatusesresponse",
          label: "assetsGetBodyStatusesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetbrandmodelsresponse",
          label: "assetsGetBrandModelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetcategoriesresponse",
          label: "assetsGetCategoriesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetcitiesresponse",
          label: "assetsGetCitiesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetcolorsresponse",
          label: "assetsGetColorsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetdistrictsresponse",
          label: "assetsGetDistrictsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetinternalstoragesresponse",
          label: "assetsGetInternalStoragesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetoauthscopesresponse",
          label: "assetsGetOAuthScopesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetoauthscopesresponseappoauthscope",
          label: "assetsGetOAuthScopesResponseAppOauthScope",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetoauthscopesresponselifecyclestate",
          label: "assetsGetOAuthScopesResponseLifeCycleState",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetpermissionsresponse",
          label: "assetsGetPermissionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetpermissionsresponselifecyclestate",
          label: "assetsGetPermissionsResponseLifeCycleState",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetpermissionsresponsepermission",
          label: "assetsGetPermissionsResponsePermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetrammemoriesresponse",
          label: "assetsGetRamMemoriesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/assetsgetservicetypesresponse",
          label: "assetsGetServiceTypesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/authorizationapicallerinfo",
          label: "authorizationAPICallerInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/دامنه-oauth-استاندارد-تجزیه-شده-با-استفاده-از-رشته-فرمت-permission-enum-resource-id-را-نمایش-می-دهد-مثال-edit-post-azroi-1-el",
          label: "دامنه oauth استاندارد تجزیه شده با استفاده از رشته فرمت\n`PERMISSION_ENUM__{resource_id}` را نمایش می‌دهد. مثال: EDIT_POST__AZrOi1eL",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapichatbotsendmessageresponse",
          label: "chatapiChatBotSendMessageResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapichatbutton",
          label: "chatapiChatButton",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapichatbuttongrid",
          label: "chatapiChatButtonGrid",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapichatbuttonrow",
          label: "chatapiChatButtonRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapiconversation",
          label: "chatapiConversation",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapiconversationsendmessageresponse",
          label: "chatapiConversationSendMessageResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapiconversationtype",
          label: "chatapiConversationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapigenerateuploadtokenrequest",
          label: "chatapiGenerateUploadTokenRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapigenerateuploadtokenresponse",
          label: "chatapiGenerateUploadTokenResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapigetconversationresponse",
          label: "chatapiGetConversationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapimessage",
          label: "chatapiMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapimessagesenderside",
          label: "chatapiMessageSenderSide",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapimessagesendertype",
          label: "chatapiMessageSenderType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/chatapimessagetype",
          label: "chatapiMessageType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazegetcarownershipstatusresponse",
          label: "darvazeGetCarOwnershipStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazegetcarownershipstatusresponsestatus",
          label: "darvazeGetCarOwnershipStatusResponseStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazeiraniancarplate",
          label: "darvazeIranianCarPlate",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazerequestcarownershipdelegationresponse",
          label: "darvazeRequestCarOwnershipDelegationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazerequestforpostcodevalidationresponse",
          label: "darvazeRequestForPostCodeValidationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazeverifycarownershipdelegationresponse",
          label: "darvazeVerifyCarOwnershipDelegationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazeverifycarownershipresponse",
          label: "darvazeVerifyCarOwnershipResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazeverifypostcodevalidationresponse",
          label: "darvazeVerifyPostCodeValidationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/darvazeverifypostcodevalidationresponsestatus",
          label: "darvazeVerifyPostCodeValidationResponseStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/eventseventbutton",
          label: "eventsEventButton",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/eventsregistereventsubscriptionrequest",
          label: "eventsRegisterEventSubscriptionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/eventsregistereventsubscriptionrequesteventtype",
          label: "eventsRegisterEventSubscriptionRequestEventType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/eventsregistereventsubscriptionresponse",
          label: "eventsRegisterEventSubscriptionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/eventssendeventresponse",
          label: "eventsSendEventResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findergetalldevelopmentpostsresponse",
          label: "finderGetAllDevelopmentPostsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findergetpostresponse",
          label: "finderGetPostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findergetuserpostsresponse",
          label: "finderGetUserPostsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findergetuserpostsresponsepost",
          label: "finderGetUserPostsResponsePost",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findergetuserrequest",
          label: "finderGetUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/finderpostextstate",
          label: "finderPostExtState",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findersearchpostitem",
          label: "finderSearchPostItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findersearchpostv-2-response",
          label: "finderSearchPostV2Response",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findersearchpostsv-2-request",
          label: "finderSearchPostsV2Request",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findersearchquery",
          label: "finderSearchQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/findersearchquerynumberrange",
          label: "finderSearchQueryNumberRange",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/finderuser",
          label: "finderUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/googlerpcstatus",
          label: "googlerpcStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/managementdevelopmentpost",
          label: "managementDevelopmentPost",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/managementpreset",
          label: "managementPreset",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentgetbalanceresponse",
          label: "paymentGetBalanceResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentgetpostpricingresponse",
          label: "paymentGetPostPricingResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentgettransactionresponse",
          label: "paymentGetTransactionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentlisttransactionsresponse",
          label: "paymentListTransactionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymentreorderpostresponse",
          label: "paymentReorderPostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymenttransaction",
          label: "paymentTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymenttransactionstate",
          label: "paymentTransactionState",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/paymenttransactiontype",
          label: "paymentTransactionType",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/payment-ticketgenerateresponse",
          label: "payment_ticketGenerateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/payment-ticketvalidaterequest",
          label: "payment_ticketValidateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/payment-ticketvalidateresponse",
          label: "payment_ticketValidateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/posteditpostresponse",
          label: "postEditPostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postgetimageuploadurlresponse",
          label: "postGetImageUploadURLResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postgetpoststatsresponse",
          label: "postGetPostStatsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postsubmitemergencyresidencepostrequest",
          label: "postSubmitEmergencyResidencePostRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postsubmitemergencyresidencepostresponse",
          label: "postSubmitEmergencyResidencePostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postsubmitpostrequest",
          label: "postSubmitPostRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/postsubmitpostresponse",
          label: "postSubmitPostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/posttemporaryresidencefields",
          label: "postTemporaryResidenceFields",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/protobufany",
          label: "protobufAny",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/protobufnullvalue",
          label: "protobufNullValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticcreatepostsemanticresponse",
          label: "semanticCreatePostSemanticResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticcreateusersemanticresponse",
          label: "semanticCreateUserSemanticResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticdeleteusersemanticresponse",
          label: "semanticDeleteUserSemanticResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticpostsemanticdeleted",
          label: "semanticPostSemanticDeleted",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticsendsemanticdeletioneventsresponse",
          label: "semanticSendSemanticDeletionEventsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "openapi-doc/schemas/semanticusersemanticdeleted",
          label: "semanticUserSemanticDeleted",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
